### ISSUE TITLE
drag lock still not enabled on Sierra

### ISSUE THREAD

**Issue by fifa2017player** [boochtek/mac_config#1]
I tried this script on Sierra and only got three finger drag.

Someone else encountered the same problem here on Sierra (Casper1811):
https://discussions.apple.com/thread/7387742?start=0&tstart=0

**Comment by booch** [comment]
Sorry, I don't have any Macs running Sierra yet, as I'm waiting for Karabiner to support it. I'm not finding anywhere explaining how to fix the problem with `defaults` from the command line. I suspect they changed the plist path, since they moved the setting into Accessibility.

I'd be happy to update, if you happen to find what command I need to update to. (Feel free to re-open this issue if you do.)
